"""empty message

Revision ID: 603729144070
Revises: 
Create Date: 2021-06-02 14:59:28.221713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603729144070'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('userid', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=False),
    sa.Column('pwd', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_table('check',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(), nullable=True),
    sa.Column('pro', sa.String(), nullable=False),
    sa.Column('datime', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('comm', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_table('keyword',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('pro', sa.String(), nullable=True),
    sa.Column('k_word1', sa.String(), nullable=False),
    sa.Column('k_word2', sa.String(), nullable=False),
    sa.Column('k_word3', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pro'], ['check.pro'], ),
    sa.PrimaryKeyConstraint('index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyword')
    op.drop_table('check')
    op.drop_table('user')
    # ### end Alembic commands ###
