"""empty message

Revision ID: 8b9b9a2ee63f
Revises: 
Create Date: 2021-05-31 17:24:40.462950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b9b9a2ee63f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check',
    sa.Column('userid', sa.String(), nullable=False),
    sa.Column('done', sa.String(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_table('user',
    sa.Column('userid', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=False),
    sa.Column('pwd', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('userid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('check')
    # ### end Alembic commands ###
