"""empty message

Revision ID: b314d534291b
Revises: 
Create Date: 2021-06-02 03:40:03.106938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b314d534291b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(), nullable=True),
    sa.Column('pro', sa.String(), nullable=True),
    sa.Column('datime', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('comm', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_table('user',
    sa.Column('userid', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=False),
    sa.Column('pwd', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('userid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('check')
    # ### end Alembic commands ###
